feat: Implement Logger
daangn/minimemcached pull request #10
Opened 2022-06-21 07:40 UTC by sang-w0o

# Implment Logger

- This PR implements Logger, which logs certain messages depending on the log level configured.   
  Log level contains of:
  - Info: Default log level, only logs informational messages.
  - Debug: Logs all incoming requests, and responses to help debugging process.
  - Off: Doesn't log anything at all.

2022-10-04 03:39 UTC, HurSungYun requested changes
I believe Logger should be declared as an Interface and minimemcached should support DefaultLogger as default implementation.

Please make Logger as an interface and convert existing logger implementation into `type DefaultLogger struct` or something.

2022-10-04 03:39 UTC, HurSungYun commented on logger.go
> +type Logger struct {
I believe Logger should be implemented as an interface.

Implementation in GORM can be a good reference. https://github.com/go-gorm/gorm/blob/master/logger/logger.go

I would suggest interface below.

```go
// Logger logger interface
type Logger interface {
	Info(string)
	Debug(string)
}
```

Furthermore,

1. Checking log level each time is inefficient
2. log levels are cascading. (e.g. INFO level logs should be printed in DEBUG log level)

2022-10-04 03:39 UTC, HurSungYun commented on minimemcached.go
> +func newMiniMemcached(lv LogLevel, opts ...Option) *MiniMemcached {
it would be better to use Options pattern for log level.

2023-03-07 04:28 UTC, sang-w0o commented
I will try to update this PR accepting @HurSungYun 's recommendations soon!

2023-05-26 05:43 UTC, novemberde commented
Please reopen the pull request as it is no longer being followed up

2023-05-26 05:43 UTC, closed without merging